### ISSUE TITLE
Добавить поддержку ARM64

### ISSUE THREAD

**Issue by MihaxXx** [veselchak24/SFUStudCompanion#13]
Это неприемлемо в 2024. Google удалил обратную совместимость c 32-bit arm из Android 14, у вас должна быть включена сборка для arm64 тоже

<details>

![image](https://github.com/veselchak24/SFUStudCompanion/assets/5885676/fce3d799-0a1b-4fd4-a195-75482983b789)
</details>

**Comment by veselchak24** [comment]
Добавлена
