### ISSUE TITLE
Проблемы с навигацией

### ISSUE THREAD

**Issue by vaimon** [veselchak24/SFUStudCompanion#6]
Кнопка назад, оказывается, спрятана за списком новостей (и иногда подлагивает при попытке её открыть), что не очень интуитивно. Плюс нельзя использовать системные клавиши навигации (но я не уверен, можно ли это как-то вообще обрабатывать на вашем стеке)

**Comment by MihaxXx** [comment]
Нужно отключить переход в полноэкранный режим. Понятно, почему это поведение по умолчанию для Unity, но для приложения, которое не игра, это неприемлемо.

**Comment by MihaxXx** [comment]
Почему это тоже не было исправлено?

**Comment by veselchak24** [comment]
Навигация, за исключением постоянного отображения кнопок исправлена.
Unity не позволяет отображать системные кнопки постоянно
