### ISSUE TITLE
Вёрстка на экране новостей мехмата поехала

### ISSUE THREAD

**Issue by vaimon** [veselchak24/SFUStudCompanion#7]
![image](https://github.com/veselchak24/SFUStudCompanion/assets/28728097/ff04ceef-1af9-4c8c-9e52-510a2366e80e)
И пересмотрите, пожалуйста, цветовую гамму. Это очень вырвиглазно выглядит.

**Comment by veselchak24** [comment]
Дизайн ленты изменён ✔
